### PR TITLE
Support custom node generators

### PR DESCRIPTION
**Pull request by tpict**
I originally planned on making `generators` a constructor argument, but that got hairy pretty quickly since there's a lot of recursive generator instantiation. This just exposes a static method for setting the generators globally.

Fixes https://github.com/papandreou/css-generators/issues/37

### CODE REVIEW

**Comment by papandreou** [comment]
Is there anyway we can keep the split out generators as direct methods on `CssSyntaxGenerator`? Seems like that would avoid the `bind`ing, and you'd still be able to override them individually without any extra apis? Either on a specific instance:

```js
cssSyntaxGenerator.generateKeyword = function (chance) {...};
```

... or globally with:

```js
CssSyntaxGenerator.prototype.generateKeyword = function (chance) {...};
```

... or even by inheritance with:

```js
class MyGenerator extends CssSyntaxGenerator {
  generateKeyword(chance) { ... }
}
```

**Comment by tpict** [comment]
Done!

**Review by papandreou — APPROVED** [review]
LGTM, thanks a lot! 🎉

**Comment by papandreou** [comment]
Released in 0.4.0

**Comment by tpict** [comment]
Thanks again!

**Pull request merged**
