### PR TITLE
Fix integers being suffixed with %

### PR DESCRIPTION
**Pull request by tpict**
The CSS validation library I'm working on caught these 🤗

### CODE REVIEW

**Comment by papandreou** [comment]
Ohh, whoopsie copy pastie, thanks!

**Comment by papandreou** [comment]
I fixed the remaining snapshots (with `UNEXPECTED_SNAPSHOT=1 npm test`) and landed it.

**Comment by papandreou** [comment]
Released in 0.3.1.

**Comment by tpict** [comment]
Thanks!

**Pull request merged**
